apiVersion: v1
kind: Service
metadata:
  name: demo-backend-service
  namespace: demo-app
spec:
  type: ClusterIP
  selector:
    app: demo-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http